import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Notice | Kharis Church',
  description: 'How Kharis Church handles your personal data in Kairos.',
};

const PRIVACY_VERSION = '2026-07-v1';
const PRIVACY_EFFECTIVE_DATE = '23 July 2026';

export default function PrivacyPage() {
  return (
    <article className="space-y-8 text-[15px] leading-relaxed text-foreground">
      <header className="space-y-2">
        <p className="text-xs font-semibold uppercase tracking-widest text-[#5D3FD3]">
          Legal
        </p>
        <h1 className="text-3xl font-bold tracking-tight">Privacy Notice</h1>
        <p className="text-sm text-muted-foreground">
          Effective {PRIVACY_EFFECTIVE_DATE} · Version {PRIVACY_VERSION}
        </p>
      </header>

      <section className="space-y-3">
        <p>
          This notice explains how Kharis Church (&ldquo;we&rdquo;,
          &ldquo;us&rdquo;, &ldquo;the church&rdquo;) collects and uses your
          personal data when you use Kairos, our internal church administration
          platform. It is written to comply with the UK General Data Protection
          Regulation (UK GDPR) and the Data Protection Act 2018.
        </p>
        <p>
          Kharis Church is the <strong>data controller</strong> for personal
          data processed in Kairos. If you have any questions about this
          notice, or you want to exercise any of the rights described below,
          please contact us at{' '}
          <a
            href="mailto:privacy@kharis.org"
            className="font-medium text-[#5D3FD3] hover:underline"
          >
            privacy@kharis.org
          </a>
          .
        </p>
      </section>

      <Section title="1. Who this notice applies to">
        <p>
          This notice applies to members of Kharis Church who create an account
          in Kairos, to people whose information is entered into Kairos by our
          leaders (for example first-time visitors captured on a welcome form,
          or children whose parents provide information on their behalf), and
          to anyone who submits information through a public Kairos form.
        </p>
      </Section>

      <Section title="2. What personal data we collect">
        <p>We collect and hold the following categories of data.</p>

        <SubHeading>2.1 Information you give us at sign-up</SubHeading>
        <ul className="list-disc space-y-1 pl-6">
          <li>Full name (first, middle, last) and any preferred honorific</li>
          <li>Email address and phone number</li>
          <li>Date of birth and gender</li>
          <li>Home and (optionally) secondary postal address</li>
          <li>The Kharis Church branch you attend</li>
          <li>Emergency contact name, relationship and phone number</li>
          <li>A password (stored only as a one-way cryptographic hash)</li>
        </ul>

        <SubHeading>2.2 Information you can add later</SubHeading>
        <ul className="list-disc space-y-1 pl-6">
          <li>A profile photo</li>
          <li>Marital status, occupation, prior church background</li>
          <li>Notification preferences</li>
        </ul>

        <SubHeading>2.3 Information generated by your church activity</SubHeading>
        <ul className="list-disc space-y-1 pl-6">
          <li>Service and fellowship attendance records</li>
          <li>Fellowship group membership and any leadership role you hold</li>
          <li>Department membership, rota assignments and uniform sizes</li>
          <li>
            New believer discipleship pipeline stage, if applicable, along with
            mentor session notes taken by your mentor
          </li>
          <li>
            Form submissions you make (for example: baptism application,
            testimony, altar-call response, baby dedication, declarative forms)
          </li>
          <li>
            Prayer requests, follow-up notes, or safeguarding notes recorded by
            a leader in connection with pastoral care
          </li>
          <li>
            Records of the consents you have given or withdrawn, and the
            versions of this notice and our Terms &amp; Conditions you have
            accepted
          </li>
        </ul>

        <SubHeading>2.4 Technical information</SubHeading>
        <ul className="list-disc space-y-1 pl-6">
          <li>Sign-in timestamps, session tokens and the browser you used</li>
          <li>
            IP address and coarse device information, used only to secure your
            account against unauthorised access
          </li>
          <li>
            Error reports automatically generated if part of Kairos fails while
            you are using it. These may incidentally include personal
            data such as the URL you were viewing at the time
          </li>
        </ul>

        <SubHeading>2.5 Special category and safeguarding data</SubHeading>
        <p>
          Where a form asks you to disclose information about your health, a
          disability, a child in your care, or a safeguarding concern, that
          information is treated with extra care. We collect it only where it
          is necessary for the pastoral and safeguarding responsibilities of
          the church, and access is restricted to leaders with a lawful reason
          to see it.
        </p>
      </Section>

      <Section title="3. Why we use your data and our legal basis">
        <p>
          Under UK GDPR we can only process your data if we have a lawful basis
          for doing so. We rely on the following bases:
        </p>

        <div className="mt-3 overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b text-left text-xs uppercase tracking-wider text-muted-foreground">
                <th className="py-2 pr-4">Purpose</th>
                <th className="py-2">Lawful basis</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              <tr>
                <td className="py-2 pr-4">
                  Administering church membership, allowing you to sign in, and
                  contacting you about services and fellowship groups you are
                  part of
                </td>
                <td className="py-2">
                  Legitimate interests of the church in caring for its members
                </td>
              </tr>
              <tr>
                <td className="py-2 pr-4">
                  Recording attendance, tracking discipleship progress, and
                  co-ordinating rotas for departments you serve in
                </td>
                <td className="py-2">
                  Legitimate interests of the church in running services and
                  ministries
                </td>
              </tr>
              <tr>
                <td className="py-2 pr-4">
                  Pastoral care, prayer follow-up and safeguarding of
                  vulnerable people (including children under 16)
                </td>
                <td className="py-2">
                  Legitimate interests, and where relevant our legal
                  obligations under safeguarding law
                </td>
              </tr>
              <tr>
                <td className="py-2 pr-4">
                  Sending you optional newsletters, event invitations, or
                  outreach communications beyond the fellowships you are part
                  of
                </td>
                <td className="py-2">Your explicit consent</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">
                  Protecting Kairos against fraud and abuse, and keeping audit
                  logs of consent and admin actions
                </td>
                <td className="py-2">
                  Legitimate interests in maintaining a secure platform
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="pt-2">
          We do not use your data for automated decision-making that
          significantly affects you, and we do not sell your data to anyone.
        </p>
      </Section>

      <Section title="4. Who we share your data with">
        <p>
          Your data is visible inside Kharis Church to leaders whose role
          requires it. For example, your fellowship leader can see your
          attendance in that fellowship, and branch administrators can see
          member information for the branch they administer. Access is scoped
          so that leaders only see the data for the people and areas they are
          responsible for.
        </p>
        <p>We share data with the following third parties who help us run Kairos:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>Cloudflare, Inc.</strong> hosts the Kairos website,
            application server, database gateway and image storage.
          </li>
          <li>
            <strong>PlanetScale, Inc.</strong> runs the Postgres
            database that stores your member record. Data is stored in the
            United Kingdom / European Economic Area (EEA).
          </li>
          <li>
            <strong>Amazon Web Services, Inc.</strong> sends the
            transactional emails Kairos generates (for example account
            verification, password reset, notification digests). Region: EU
            (London / Frankfurt).
          </li>
          <li>
            <strong>Sentry, Inc.</strong> receives error reports when
            Kairos fails, so we can diagnose and fix issues.
          </li>
        </ul>
        <p>
          These providers act as <em>data processors</em>: they process your
          data only under our instructions and are bound by contract to
          protect it. Where a provider transfers data outside the UK / EEA, we
          rely on the UK International Data Transfer Agreement or Standard
          Contractual Clauses adopted by the UK / EU to keep the data
          protected to an equivalent standard.
        </p>
        <p>
          We may also disclose data where we are legally required to do so,
          for example in response to a safeguarding investigation, a
          court order, or a request from a UK regulator.
        </p>
      </Section>

      <Section title="5. How long we keep your data">
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Active member records</strong> are kept for as long as you
            remain a member of Kharis Church.
          </li>
          <li>
            <strong>Archived member records</strong> are kept for up to 6 years
            after you leave, so that we can respond to safeguarding queries
            and demonstrate compliance with this notice. After that period we
            anonymise or delete the record.
          </li>
          <li>
            <strong>Records about children under 16</strong> are kept in
            line with our safeguarding policy. When a child turns 18, their
            record transitions to the standard adult retention above.
          </li>
          <li>
            <strong>Attendance records</strong> are kept for 3 years on a
            rolling basis for reporting.
          </li>
          <li>
            <strong>Consent records</strong> are kept for the lifetime of
            your account plus 6 years, because they are our evidence that we
            processed data lawfully.
          </li>
          <li>
            <strong>Sign-in logs and error reports</strong> are kept for
            up to 90 days, then automatically deleted.
          </li>
        </ul>
      </Section>

      <Section title="6. Your rights">
        <p>Under UK GDPR you have the right to:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Access</strong> your personal data (a &ldquo;subject
            access request&rdquo;)
          </li>
          <li>
            <strong>Correct</strong> data that is inaccurate or incomplete.
            You can do most of this yourself from your profile screen
          </li>
          <li>
            <strong>Erase</strong> your data (&ldquo;the right to be
            forgotten&rdquo;), except where we are required to keep it for
            safeguarding or legal reasons
          </li>
          <li>
            <strong>Restrict</strong> how we process your data while a query
            is being resolved
          </li>
          <li>
            <strong>Portability</strong>: receive a machine-readable
            export of the data you gave us
          </li>
          <li>
            <strong>Object</strong> to processing carried out on the basis of
            our legitimate interests
          </li>
          <li>
            <strong>Withdraw consent</strong> at any time, where we relied on
            consent. For example, unsubscribing from optional
            newsletters on{' '}
            <Link
              href="/profile/settings/legal"
              className="font-medium text-[#5D3FD3] hover:underline"
            >
              your legal &amp; consent settings
            </Link>
          </li>
        </ul>
        <p>
          To exercise any of these rights, email us at{' '}
          <a
            href="mailto:privacy@kharis.org"
            className="font-medium text-[#5D3FD3] hover:underline"
          >
            privacy@kharis.org
          </a>
          . We will respond within one calendar month.
        </p>
        <p>
          If you believe we have handled your data unlawfully, you can
          complain to the UK Information Commissioner&rsquo;s Office at{' '}
          <a
            href="https://ico.org.uk"
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-[#5D3FD3] hover:underline"
          >
            ico.org.uk
          </a>
          . We would encourage you to raise the issue with us first so that
          we can put it right.
        </p>
      </Section>

      <Section title="7. Children and young people">
        <p>
          Kharis Church takes the safeguarding of children very seriously. If
          you are under 16, please ask a parent or guardian to complete
          Kairos-related forms on your behalf. Children&rsquo;s records are
          created and managed by a parent or a designated safeguarding lead,
          and their visibility inside Kairos is restricted to leaders whose
          role requires them to see it. When a child reaches an appropriate
          age, we support them in taking over their own record.
        </p>
      </Section>

      <Section title="8. Cookies and tracking">
        <p>
          Kairos uses a single first-party cookie to keep you signed in
          during a session. We do not use advertising cookies, we do not run
          third-party analytics that track you across the web, and we do not
          share your usage patterns with marketing platforms.
        </p>
      </Section>

      <Section title="9. Security">
        <p>
          Passwords are stored as one-way cryptographic hashes and cannot be
          read by anyone, including us. Data in transit is protected by TLS.
          Access to Kairos administration is gated by role-based permissions
          and audit-logged. We keep our platform patched and monitored, and
          run regular reviews of who has access to what.
        </p>
      </Section>

      <Section title="10. Changes to this notice">
        <p>
          When we make a material change to this notice we will bump its
          version and ask you to review and accept it the next time you sign
          in. Minor typo-level changes may be made without prompting.
        </p>
      </Section>

      <Section title="11. Contact us">
        <p>
          Kharis Church:{' '}
          <a
            href="mailto:privacy@kharis.org"
            className="font-medium text-[#5D3FD3] hover:underline"
          >
            privacy@kharis.org
          </a>
        </p>
      </Section>

      <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-4 text-xs text-amber-900 dark:text-[#f8b537]">
        <p className="font-semibold">Draft for review</p>
        <p className="mt-1">
          This document is an initial draft written from what Kairos actually
          collects and how it is stored. It has not yet been reviewed by
          Kharis Church leadership or a data-protection professional. Please
          treat it as a starting point rather than a settled policy.
        </p>
      </div>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
      {children}
    </section>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="pt-3 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
      {children}
    </h3>
  );
}
