import './global.css';
import { CognitoAuthProvider } from '../components/auth-provider';

export const metadata = {
  title: 'Welcome to apps',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CognitoAuthProvider>
          {children}
        </CognitoAuthProvider>
      </body>
    </html>
  );
}
